### PR TITLE
AMQ-8316 Removed unused BrokerService methods

### PR DESCRIPTION
**Pull request by ehossack-aws**
These are the methods that are unused, both in code, but also that are not used by embedded brokers to our knowledge.

### CODE REVIEW

**Comment by Charlie-chenchrl** [comment]
All checks have failed: https://us-west-2.console.aws.amazon.com/codesuite/codebuild/187045623040/projects/ehossack-activemq/build/ehossack-activemq%3A51bffa75-454c-4c48-a46b-9d910a357a92

**Comment by ehossack-aws** [comment]
> All checks have failed: https://us-west-2.console.aws.amazon.com/codesuite/codebuild/187045623040/projects/ehossack-activemq/build/ehossack-activemq%3A51bffa75-454c-4c48-a46b-9d910a357a92

Have you managed to get a passing build?

**Comment by Charlie-chenchrl** [comment]
except unit-tests yes: https://github.com/Charlie-chenchrl/activemq/runs/3374896964?check_suite_focus=true

**Comment by Charlie-chenchrl** [comment]
All checks have passed! LGTM!

**Review by Charlie-chenchrl — APPROVED** [review]

**Pull request closed without merging**
